// <auto-generated />
using DataConsole.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataConsole.DAL.Migrations
{
    [DbContext(typeof(DataConsoleDbContext))]
    [Migration("20220217013607_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataConsole.Core.Something", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Somethings");
                });

            modelBuilder.Entity("DataConsole.Core.SomethingElse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SomethingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SomethingId");

                    b.ToTable("SomethingElses");
                });

            modelBuilder.Entity("DataConsole.Core.SomethingElse", b =>
                {
                    b.HasOne("DataConsole.Core.Something", "MySomething")
                        .WithMany("SomethingElses")
                        .HasForeignKey("SomethingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MySomething");
                });

            modelBuilder.Entity("DataConsole.Core.Something", b =>
                {
                    b.Navigation("SomethingElses");
                });
#pragma warning restore 612, 618
        }
    }
}
